# ansible-playbook -i ec2.py commoncluster.yml --limit tag_Name_stage-edx-commoncluster -e@/path/to/vars/env-deployment.yml -T 30 --list-hosts

- hosts: all
  sudo: True
  serial: 1
  vars:
    ENABLE_DATADOG: False
    ENABLE_SPLUNKFORWARDER: False
    ENABLE_NEWRELIC: False
  roles:
    - aws
    - role: nginx
      nginx_sites:
      - xqueue
    - role: xqueue
    - role: datadog
      when: ENABLE_DATADOG
    - role: splunkforwarder
      when: ENABLE_SPLUNKFORWARDER
    - role: newrelic
      when: ENABLE_NEWRELIC
    - oraclejdk
    - elasticsearch
    - rabbitmq
    - datadog
    - splunkforwarder

#
# In order to reconfigure the host resolution we are issuing a
# reboot.
# TODO: We should probably poll to ensure the host comes back before moving
# to the next host so that we don't reboot all of the servers simultaneously
- hosts: all
  sudo: True
  serial: 1
  vars:
    reboot: False
  tasks:
    - name: reboot
      command: /sbin/shutdown -r now "Reboot is triggered by Ansible"
      when: reboot
      tags: reboot
