- name: Deploy rabbitmq
  hosts: all
  sudo: True
  # The rabbitmq role depends on
  # ansible_default_ipv4 so
  # gather_facts must be set to True
  gather_facts: True
  roles:
    - aws
    - rabbitmq
