---
- name: create application user
  user: >
    name="{{ badgekit_user }}" home="{{ badgekit_app_dir }}"
    createhome=no shell=/bin/false
    
- name: create badgekit user dirs
  file: >
    path="{{ item }}" state=directory
    owner="{{ badgekit_user }}" group="{{ common_web_group }}"
  with_items:
    - "{{ badgekit_app_dir }}"
    - "{{ badgekit_server_dir }}"
    - "{{ badgekit_api_server_dir }}" 

# Do A Checkout
- name: checkout badgekit_server repo into {{badgekit_server_dir}}
  git: dest={{badgekit_server_dir}} repo={{badgekit_server_repo}} version={{badgekit_server_version}}
  register: chkout
  sudo_user: "{{ badgekit_user }}"
  environment:
    GIT_SSH: "{{ edxapp_git_ssh }}"

# Do A Checkout
- name: checkout badgekit_api_server repo into {{badgekit_api_server_dir}}
  git: dest={{badgekit_api_server_dir}} repo={{badgekit_api_server_repo}} version={{badgekit_api_server_version}}
  register: chkout
  sudo_user: "{{ badgekit_user }}"
  environment:
    GIT_SSH: "{{ edxapp_git_ssh }}"

- name: Do nmp install for openbadges
  sudo_user: "{{ badgekit_user }}"
  npm: path="{{badgekit_server_dir}}" state=present registry=http://registry.npmjs.org/

- name: Do nmp install for badgekit_api_server
  sudo_user: "{{ badgekit_user }}"
  npm: path="{{badgekit_api_server_dir}}" state=present registry=http://registry.npmjs.org/


- name: Create Badgekit_api Database
  mysql_db: >
    db={{badgekit_api_server_mysqldb}}
    state=present
    encoding=utf8
  when: EDXAPP_MYSQL_USER is defined

- name: Create database for Openbadges server
  mysql_db: >
    db={{badgekit_server_mysqldb}}
    state=present
    encoding=utf8
  when: EDXAPP_MYSQL_USER is defined

- name: setup the Badgekit_api_server_ env
  template: >
    src=badgekit_api_env.j2 dest={{badgekit_api_server_dir}}/.env
    owner={{ badgekit_user }}  group={{ common_web_user }}
    mode=0644

- name: setup the Openbadges_server config.json
  template: > 
    src=badgekit_server.config.j2 dest={{badgekit_server_dir}}/config.json
    owner={{ badgekit_user }}  group={{ common_web_user }}
    mode=0644

- name: DB Migration for Badgekit_api
  command: bin/db-migrate up chdir={{badgekit_api_server_dir}}
  notify: restart badgekitapi

- name: DB Migration for Openbadges_server
  command: bin/db-migrate up chdir={{badgekit_server_dir}} 
  notify: restart badgekit

- include: deploy.yml tags=deploy


