- name: Configure instance(s)
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    openid_workaround: True
    devstack: True
    disable_edx_services: False
    edx_platform_version: 'master'
    mongo_enable_journal: False
    EDXAPP_NO_PREREQ_INSTALL: 0
    COMMON_MOTD_TEMPLATE: "devstack_motd.tail.j2"
  vars_files:
    - "group_vars/all"
  roles:
    - badgekit